name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Check go mod
      run: |
        go mod tidy
        git diff --exit-code go.mod
        git diff --exit-code go.sum
    - run: gofmt -s -d .
    - run: go build -v ./cmd/polyjson
    - run: ./polyjson -type Shape -package ./testdata
    - run: gofmt -s -d testdata/polyjsongen.go
    - run: go test -test.v -race -cover ./...
    - run: go test -test.v -race -cover ./testdata
