name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - run: go get -v -t -d ./...
    - run: gofmt -s -d .
    - run: go build -v
    - run: go test -test.v -race -cover ./...

  go-mod-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - run: |
        go mod tidy
        git diff --exit-code go.mod
        git diff --exit-code go.sum
